.TH "/home/jenny/RL/rl_only/include/rl/Action.h" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jenny/RL/rl_only/include/rl/Action.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrl::ActionBase\fP"
.br
.RI "\fIBase class for all action types to be performed\&. This must include ALL possible actions in a domain within the SAME implementing subclass\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
