.TH "/home/jenny/RL/rl_only/include/rl/Controller.h" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jenny/RL/rl_only/include/rl/Controller.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <rl/Policy\&.h>\fP
.br
\fC#include <rl/Transition\&.h>\fP
.br
\fC#include <rl/Utility\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrl::LearningController< Domain, StateUtilityDatatype >\fP"
.br
.RI "\fIInterface to learning algorithms\&. After setting the initial state of the environment for the learner, it can be used to update the state each time step\&. Internally, each state will lead to a recommended action by the learner, which in turn can be used to transfer the system into a new state\&. This will have to be done outside this class, e\&.g\&. in a subclass of \fBDomain\fP, which in turn uses the transition function to transfer between states\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
