.TH "/home/jenny/RL/rl_only/include/rl/Domain.h" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jenny/RL/rl_only/include/rl/Domain.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <rl/Transition\&.h>\fP
.br
\fC#include <rl/Reward\&.h>\fP
.br
\fC#include <rl/StateAlgorithms\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrl::Domain< State, Action >\fP"
.br
.RI "\fIBase class for all domains, implementing certain aspects which need domain knowledge\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
