.TH "/home/jenny/RL/rl_only/include/rl/Exploration.h" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jenny/RL/rl_only/include/rl/Exploration.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrl::Exploration< UtilityValue, FrequencyType >\fP"
.br
.RI "\fIInterface for an exploration function, taking an utility value (e\&.g\&. q-value) and a frequency of an action tried in a state as input, and returning a utility value\&. \fP"
.ti -1c
.RI "class \fBrl::SimpleExploration< UtilityValue, FrequencyType >\fP"
.br
.ti -1c
.RI "class \fBrl::NoExploration< UtilityValue, FrequencyType >\fP"
.br
.ti -1c
.RI "class \fBrl::LearningRate\fP"
.br
.ti -1c
.RI "class \fBrl::DecayLearningRate\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
