.TH "/home/jenny/RL/rl_only/include/rl/GridWorld.h" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jenny/RL/rl_only/include/rl/GridWorld.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <rl/StateAlgorithms\&.h>\fP
.br
\fC#include <rl/State\&.h>\fP
.br
\fC#include <rl/Domain\&.h>\fP
.br
\fC#include <math/RandomNumber\&.h>\fP
.br
\fC#include <general/Exception\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrl::GridWorldState\fP"
.br
.RI "\fIState of the grid world\&. \fP"
.ti -1c
.RI "class \fBrl::MoveAction\fP"
.br
.RI "\fIAction to move in the grid world\&. \fP"
.ti -1c
.RI "class \fBrl::GridWorldStateGenerator\fP"
.br
.RI "\fIGenerates states for the grid world\&. \fP"
.ti -1c
.RI "class \fBrl::GridWorldActionGenerator\fP"
.br
.RI "\fIGenerates actions for the grid world\&. \fP"
.ti -1c
.RI "class \fBrl::GridWorldTransition\fP"
.br
.RI "\fISimple transition function which is known a priori for the grid world and does not have to be learned\&. \fP"
.ti -1c
.RI "class \fBrl::GridDomain\fP"
.br
.RI "\fIthe \fBDomain\fP of the grid world\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
