.TH "/home/jenny/RL/rl_only/include/math/RandomNumber.h" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jenny/RL/rl_only/include/math/RandomNumber.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <stdio\&.h>\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <time\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBRandomNumberGenerator\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBRandomNumberGenerator\fP \fB_randomNumber\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "\fBRandomNumberGenerator\fP _randomNumber"

.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
