.TH "RandomNumberGenerator" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RandomNumberGenerator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RandomNumber\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRandomNumberGenerator\fP ()"
.br
.ti -1c
.RI "\fB~RandomNumberGenerator\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static int \fBrandom\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface to random number generator, as defined by srand() and rand() functions\&. srand(time(NULL)) is called in constructor, and function rand() behaves as the c rand() function\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RandomNumberGenerator::RandomNumberGenerator ()\fC [inline]\fP"

.SS "RandomNumberGenerator::~RandomNumberGenerator ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "static int RandomNumberGenerator::random ()\fC [inline]\fP, \fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
