.TH "/home/jenny/RL/rl_only/include/rl/Reward.h" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jenny/RL/rl_only/include/rl/Reward.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include <deque>\fP
.br
\fC#include <rl/LogBinding\&.h>\fP
.br
\fC#include <general/Exception\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrl::Reward< State, Value >\fP"
.br
.RI "\fIImplements the reward function\&. This can be a function or a lookup in a table\&. \fP"
.ti -1c
.RI "class \fBrl::SelectedReward< State, Value >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
