.TH "rl::DecayLearningRate" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rl::DecayLearningRate \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exploration\&.h>\fP
.PP
Inherits \fBrl::LearningRate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecayLearningRate\fP (float _decayRate=1e-01)"
.br
.ti -1c
.RI "virtual \fB~DecayLearningRate\fP ()"
.br
.ti -1c
.RI "virtual float \fBget\fP (unsigned int freq) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBdecayRate\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "rl::DecayLearningRate::DecayLearningRate (float _decayRate = \fC1e-01\fP)\fC [inline]\fP"

.SS "virtual rl::DecayLearningRate::~DecayLearningRate ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual float rl::DecayLearningRate::get (unsigned int freq) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBrl::LearningRate\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float rl::DecayLearningRate::decayRate\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
