.TH "rl::GridWorldStateGenerator" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rl::GridWorldStateGenerator \- Generates states for the grid world\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GridWorld\&.h>\fP
.PP
Inherits \fBrl::StateGenerator< GridWorldState >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBStateAlgorithm\fP< \fBGridWorldState\fP > \fBStateAlgorithmT\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGridWorldStateGenerator\fP (unsigned int _maxX, unsigned int _maxY, unsigned int _blockX, unsigned int _blockY)"
.br
.ti -1c
.RI "virtual \fB~GridWorldStateGenerator\fP ()"
.br
.ti -1c
.RI "virtual bool \fBforeachState\fP (\fBStateAlgorithmT\fP &s) const "
.br
.ti -1c
.RI "virtual \fBGridWorldState\fP \fBrandomState\fP () const "
.br
.in -1c
.SH "Detailed Description"
.PP 
Generates states for the grid world\&. 


.PP
\fBAuthor:\fP
.RS 4
Jennifer Buehler 
.RE
.PP
\fBDate:\fP
.RS 4
May 2011 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "typedef \fBStateAlgorithm\fP<\fBGridWorldState\fP> \fBrl::GridWorldStateGenerator::StateAlgorithmT\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "rl::GridWorldStateGenerator::GridWorldStateGenerator (unsigned int _maxX, unsigned int _maxY, unsigned int _blockX, unsigned int _blockY)\fC [inline]\fP"

.PP
\fBParameters:\fP
.RS 4
\fI_maxX\fP and _maxY: dimensions of the grid world 
.br
\fI_blockX\fP and _blockY: where the block is placed in the world\&. 
.RE
.PP

.SS "virtual rl::GridWorldStateGenerator::~GridWorldStateGenerator ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual bool rl::GridWorldStateGenerator::foreachState (\fBStateAlgorithmT\fP & s) const\fC [inline]\fP, \fC [virtual]\fP"

.SS "virtual \fBGridWorldState\fP rl::GridWorldStateGenerator::randomState () const\fC [inline]\fP, \fC [virtual]\fP"
Generates a random state 
.PP
Implements \fBrl::StateGenerator< GridWorldState >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
