.TH "rl::LearningRate" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rl::LearningRate \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Exploration\&.h>\fP
.PP
Inherited by \fBrl::DecayLearningRate\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef std::shared_ptr< \fBLearningRate\fP > \fBLearningRatePtrT\fP"
.br
.ti -1c
.RI "typedef std::shared_ptr< const \fBLearningRate\fP > \fBLearningRateConstPtrT\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLearningRate\fP (float initialValue)"
.br
.ti -1c
.RI "virtual \fB~LearningRate\fP ()"
.br
.ti -1c
.RI "virtual float \fBget\fP (unsigned int freq) const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "float \fBlearnRate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Interface to keep a learning rate, either decaying in different ways (subclasses of this) or not deaying (this class) 
.SH "Member Typedef Documentation"
.PP 
.SS "typedef std::shared_ptr<const \fBLearningRate\fP> \fBrl::LearningRate::LearningRateConstPtrT\fP"

.SS "typedef std::shared_ptr<\fBLearningRate\fP> \fBrl::LearningRate::LearningRatePtrT\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "rl::LearningRate::LearningRate (float initialValue)\fC [inline]\fP"

.SS "virtual rl::LearningRate::~LearningRate ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual float rl::LearningRate::get (unsigned int freq) const\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented in \fBrl::DecayLearningRate\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "float rl::LearningRate::learnRate\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
