.TH "rl::PolicyGenerationAlgorithm< State, Action, UtilityDatatype >" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rl::PolicyGenerationAlgorithm< State, Action, UtilityDatatype > \- Generates a policy out of a utility and transition function\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ValueIteration\&.h>\fP
.PP
Inherits \fBrl::StateAlgorithm< State >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef State \fBStateT\fP"
.br
.ti -1c
.RI "typedef Action \fBActionT\fP"
.br
.ti -1c
.RI "typedef UtilityDatatype \fBUtilityDatatypeT\fP"
.br
.ti -1c
.RI "typedef \fBPolicyGenerationAlgorithm\fP< \fBStateT\fP, \fBActionT\fP, \fBUtilityDatatypeT\fP > \fBPolicyGenerationAlgorithmT\fP"
.br
.ti -1c
.RI "typedef std::shared_ptr< \fBPolicyGenerationAlgorithmT\fP > \fBPolicyGenerationAlgorithmPtrT\fP"
.br
.ti -1c
.RI "typedef \fBUtility\fP< \fBStateT\fP, \fBUtilityDatatypeT\fP > \fBUtilityT\fP"
.br
.ti -1c
.RI "typedef \fBActionGenerator\fP< \fBActionT\fP > \fBActionGeneratorT\fP"
.br
.ti -1c
.RI "typedef \fBTransition\fP< \fBStateT\fP, \fBActionT\fP > \fBTransitionT\fP"
.br
.ti -1c
.RI "typedef \fBPolicy\fP< \fBStateT\fP, \fBActionT\fP > \fBPolicyT\fP"
.br
.ti -1c
.RI "typedef \fBLookupPolicy\fP< \fBStateT\fP, \fBActionT\fP > \fBLookupPolicyT\fP"
.br
.ti -1c
.RI "typedef \fBMaxUtilityActionAlgorithm\fP< \fBStateT\fP, \fBActionT\fP > \fBMaxUtilityActionAlgorithmT\fP"
.br
.ti -1c
.RI "typedef \fBTransitionT::TransitionConstPtrT\fP \fBTransitionConstPtrT\fP"
.br
.ti -1c
.RI "typedef \fBUtilityT::UtilityConstPtrT\fP \fBUtilityConstPtrT\fP"
.br
.ti -1c
.RI "typedef \fBActionGeneratorT::ActionGeneratorConstPtrT\fP \fBActionGeneratorConstPtrT\fP"
.br
.ti -1c
.RI "typedef \fBPolicyT::PolicyPtrT\fP \fBPolicyPtrT\fP"
.br
.ti -1c
.RI "typedef \fBPolicyT::PolicyConstPtrT\fP \fBPolicyConstPtrT\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolicyGenerationAlgorithm\fP (const \fBTransitionConstPtrT\fP &t, const \fBUtilityConstPtrT\fP &u, const \fBActionGeneratorConstPtrT\fP &a)"
.br
.ti -1c
.RI "virtual \fB~PolicyGenerationAlgorithm\fP ()"
.br
.ti -1c
.RI "virtual bool \fBapply\fP (const \fBStateT\fP &s)"
.br
.ti -1c
.RI "\fBPolicyPtrT\fP \fBgetPolicy\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class State, class Action, typename UtilityDatatype>class rl::PolicyGenerationAlgorithm< State, Action, UtilityDatatype >"
Generates a policy out of a utility and transition function\&. 


.PP
\fBAuthor:\fP
.RS 4
Jennifer Buehler 
.RE
.PP
\fBDate:\fP
.RS 4
May 2011 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "template<class State , class Action , typename UtilityDatatype > typedef \fBActionGeneratorT::ActionGeneratorConstPtrT\fP \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBActionGeneratorConstPtrT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef \fBActionGenerator\fP<\fBActionT\fP> \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBActionGeneratorT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef Action \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBActionT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef \fBLookupPolicy\fP<\fBStateT\fP,\fBActionT\fP> \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBLookupPolicyT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef \fBMaxUtilityActionAlgorithm\fP<\fBStateT\fP,\fBActionT\fP> \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBMaxUtilityActionAlgorithmT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef \fBPolicyT::PolicyConstPtrT\fP \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBPolicyConstPtrT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef std::shared_ptr<\fBPolicyGenerationAlgorithmT\fP> \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBPolicyGenerationAlgorithmPtrT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef \fBPolicyGenerationAlgorithm\fP<\fBStateT\fP,\fBActionT\fP,\fBUtilityDatatypeT\fP> \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBPolicyGenerationAlgorithmT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef \fBPolicyT::PolicyPtrT\fP \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBPolicyPtrT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef \fBPolicy\fP<\fBStateT\fP,\fBActionT\fP> \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBPolicyT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef State \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBStateT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef \fBTransitionT::TransitionConstPtrT\fP \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBTransitionConstPtrT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef \fBTransition\fP<\fBStateT\fP,\fBActionT\fP> \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBTransitionT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef \fBUtilityT::UtilityConstPtrT\fP \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBUtilityConstPtrT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef UtilityDatatype \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBUtilityDatatypeT\fP"

.SS "template<class State , class Action , typename UtilityDatatype > typedef \fBUtility\fP<\fBStateT\fP,\fBUtilityDatatypeT\fP> \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBUtilityT\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class State , class Action , typename UtilityDatatype > \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::\fBPolicyGenerationAlgorithm\fP (const \fBTransitionConstPtrT\fP & t, const \fBUtilityConstPtrT\fP & u, const \fBActionGeneratorConstPtrT\fP & a)\fC [inline]\fP"

.SS "template<class State , class Action , typename UtilityDatatype > virtual \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::~\fBPolicyGenerationAlgorithm\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class State , class Action , typename UtilityDatatype > virtual bool \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::apply (const \fBStateT\fP & s)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBrl::StateAlgorithm< State >\fP\&.
.SS "template<class State , class Action , typename UtilityDatatype > \fBPolicyPtrT\fP \fBrl::PolicyGenerationAlgorithm\fP< State, Action, UtilityDatatype >::getPolicy ()\fC [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
