.TH "rl::StateAlgorithm< State >" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rl::StateAlgorithm< State > \- An algorithm to operate on one State object\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <StateAlgorithms\&.h>\fP
.PP
Inherited by \fBrl::PolicyGenerationAlgorithm< State, Action, UtilityDatatype >\fP, \fBrl::PolicyInitialisation< State, Action >\fP, \fBrl::PolicyIterationUpdate< State, Action >\fP, and \fBrl::ValueIterationUpdate< State, Action >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef State \fBStateT\fP"
.br
.ti -1c
.RI "typedef std::shared_ptr< State > \fBStatePtrT\fP"
.br
.ti -1c
.RI "typedef std::shared_ptr< const State > \fBStateConstPtrT\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStateAlgorithm\fP ()"
.br
.ti -1c
.RI "virtual \fB~StateAlgorithm\fP ()"
.br
.ti -1c
.RI "virtual bool \fBapply\fP (const \fBStateT\fP &s)=0"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<class State>class rl::StateAlgorithm< State >"
An algorithm to operate on one State object\&. 


.PP
\fBAuthor:\fP
.RS 4
Jennifer Buehler 
.RE
.PP
\fBDate:\fP
.RS 4
May 2011 
.RE
.PP

.SH "Member Typedef Documentation"
.PP 
.SS "template<class State > typedef std::shared_ptr<const State> \fBrl::StateAlgorithm\fP< State >::\fBStateConstPtrT\fP"

.SS "template<class State > typedef std::shared_ptr<State> \fBrl::StateAlgorithm\fP< State >::\fBStatePtrT\fP"

.SS "template<class State > typedef State \fBrl::StateAlgorithm\fP< State >::\fBStateT\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class State > \fBrl::StateAlgorithm\fP< State >::\fBStateAlgorithm\fP ()\fC [inline]\fP"

.SS "template<class State > virtual \fBrl::StateAlgorithm\fP< State >::~\fBStateAlgorithm\fP ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class State > virtual bool \fBrl::StateAlgorithm\fP< State >::apply (const \fBStateT\fP & s)\fC [pure virtual]\fP"

.PP
Implemented in \fBrl::PolicyInitialisation< State, Action >\fP, \fBrl::ValueIterationUpdate< State, Action >\fP, \fBrl::PolicyIterationUpdate< State, Action >\fP, and \fBrl::PolicyGenerationAlgorithm< State, Action, UtilityDatatype >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
