.TH "rl::Transition< State, Action, StateActionStateValue >::StateTransition" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rl::Transition< State, Action, StateActionStateValue >::StateTransition \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Transition\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStateTransition\fP (const State &_s, const \fBStateActionStateValueT\fP &_p)"
.br
.ti -1c
.RI "\fBStateTransition\fP (const \fBStateTransition\fP &o)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBStateTransition\fP &t) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "State \fBs\fP"
.br
.ti -1c
.RI "\fBStateActionStateValueT\fP \fBp\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "std::ostream & \fBoperator<<\fP (std::ostream &o, const \fBStateTransition\fP &t)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<class State, class Action, typename StateActionStateValue = float> \fBrl::Transition\fP< State, Action, StateActionStateValue >::StateTransition::StateTransition (const State & _s, const \fBStateActionStateValueT\fP & _p)\fC [inline]\fP, \fC [explicit]\fP"

.SS "template<class State, class Action, typename StateActionStateValue = float> \fBrl::Transition\fP< State, Action, StateActionStateValue >::StateTransition::StateTransition (const \fBStateTransition\fP & o)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<class State, class Action, typename StateActionStateValue = float> bool \fBrl::Transition\fP< State, Action, StateActionStateValue >::StateTransition::operator< (const \fBStateTransition\fP & t) const\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class State, class Action, typename StateActionStateValue = float> std::ostream& operator<< (std::ostream & o, const \fBStateTransition\fP & t)\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<class State, class Action, typename StateActionStateValue = float> \fBStateActionStateValueT\fP \fBrl::Transition\fP< State, Action, StateActionStateValue >::StateTransition::p"

.SS "template<class State, class Action, typename StateActionStateValue = float> State \fBrl::Transition\fP< State, Action, StateActionStateValue >::StateTransition::s"


.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
