.TH "/home/jenny/RL/rl_only/include/rl/StateAlgorithms.h" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/jenny/RL/rl_only/include/rl/StateAlgorithms.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <memory>\fP
.br
\fC#include <rl/State\&.h>\fP
.br
\fC#include <rl/Action\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBrl::StateAlgorithm< State >\fP"
.br
.RI "\fIAn algorithm to operate on one State object\&. \fP"
.ti -1c
.RI "class \fBrl::ActionAlgorithm< Action >\fP"
.br
.RI "\fIAn algorithm to operate on one Action object\&. \fP"
.ti -1c
.RI "class \fBrl::StateGenerator< State >\fP"
.br
.RI "\fIIterates through all possible states by generating each possible state (or a random set of states) and applying a \fBStateAlgorithm\fP to each state\&. Knowledge of underlying domain (e\&.g\&. grid world) is to be used to generate states\&. \fP"
.ti -1c
.RI "class \fBrl::ActionGenerator< Action >\fP"
.br
.RI "\fIIterates through all possible action by generating each possible action and applying an \fBActionAlgorithm\fP to each one\&. Knowledge of underlying domain (e\&.g\&. grid world actions up,down\&.\&.\&.) is to be used to generate actions\&. \fP"
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBrl\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
