.TH "StdLog" 3 "Wed Oct 28 2015" "LearningAlgorithms" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StdLog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <LogBinding\&.h>\fP
.PP
Inherits \fBLog\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for LearningAlgorithms from the source code\&.
