#ifndef ___EXCEPTION_H_
#define ___EXCEPTION_H_

#include <exception>
#include <string>
#include <stdio.h>


/**
 * An exception generated by a robot component.
 */
class Exception : public std::exception {
protected:
	/**
	 * A textual description of the exception.
	 */
	std::string description;
public:	
	/**
	 *
	 */
	Exception(std::string description, std::string file="", int line=0);
	
	/**
	 *
	 */
	virtual ~Exception() throw () {}
	
	/**
	 *
	 */
	virtual const char* what() const throw();
	
	/**
	 *
	 */
	std::string getDescription() {
		return description;
	}
};


#endif 
