#ifndef GENERAL_EXCEPTION_H
#define GENERAL_EXCEPTION_H
// Copyright Jennifer Buehler

#include <exception>
#include <string>
#include <stdio.h>


/**
 * An exception generated by a robot component.
 */
class Exception : public std::exception
{
protected:
    /**
     * A textual description of the exception.
     */
    std::string description;
public:
    /**
     *
     */
    explicit Exception(std::string description, std::string file = "", int line = 0);

    /**
     *
     */
    virtual ~Exception() throw() {}

    /**
     *
     */
    virtual const char* what() const throw();

    /**
     *
     */
    std::string getDescription()
    {
        return description;
    }
};


#endif  // GENERAL_EXCEPTION_H
